export const AccountEvents = {
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  ACCOUNT_CHANGED: 'ACCOUNT_CHANGED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_ENABLED: 'ACCOUNT_ENABLED',
  BALANCE_UPDATED: 'BALANCE_UPDATED',
}

export const TransactionEvents = {
  TRANSACTION_DEPOSIT: 'TRANSACTION_DEPOSIT',
}
